// Package server wires the Access Virtual Workspace binary together:
// the shared access graph, the RBAC provider that populates it, and a
// virtual-workspace root apiserver (kcp virtual-workspace-framework)
// serving two virtual workspaces behind kcp's front-proxy:
//
//   - "access" at /services/access — the SCAR API
//     (apis/access.kcp.io/v1alpha1/selfclusteraccessreviews)
//   - "mcp" at /services/mcp — MCP over streamable HTTP
//
// The root apiserver's filter chain handles authentication (front-proxy
// requestheader certs, bearer-token TokenReview against kcp, client
// certs), audit, and per-VW authorization. Both VWs read from the same
// in-process graph — the MCP VW never does an HTTP round-trip to SCAR.
package server

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/apiserver/pkg/authorization/authorizer"
	"k8s.io/apiserver/pkg/authorization/union"
	openapinamer "k8s.io/apiserver/pkg/endpoints/openapi"
	genericapiserver "k8s.io/apiserver/pkg/server"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/klog/v2"
	netutils "k8s.io/utils/net"

	"github.com/kcp-dev/virtual-workspace-framework/pkg/rootapiserver"

	accessv1alpha1 "github.com/cnvergence/kcp-access-vw/pkg/apis/access/v1alpha1"
	generatedopenapi "github.com/cnvergence/kcp-access-vw/pkg/generated/openapi"
	"github.com/cnvergence/kcp-access-vw/pkg/graph"
	"github.com/cnvergence/kcp-access-vw/pkg/rbacprovider"
	"github.com/cnvergence/kcp-access-vw/pkg/virtual"
	"github.com/cnvergence/kcp-access-vw/pkg/virtual/mcp"
	"github.com/cnvergence/kcp-access-vw/pkg/virtual/scar"
)

// Run starts the provider and serves both virtual workspaces until ctx
// is cancelled.
func Run(ctx context.Context, o *Options) error {
	if err := o.Complete(); err != nil {
		return err
	}
	if err := o.Validate(); err != nil {
		return err
	}

	restConfig, err := clientcmd.BuildConfigFromFlags("", o.Kubeconfig)
	if err != nil {
		return fmt.Errorf("load kubeconfig: %w", err)
	}

	// ── access graph + RBAC provider ────────────────────────────────

	g := graph.New()

	provider := rbacprovider.New(o.EndpointBase)
	provider.RestConfig = restConfig
	provider.APIExportEndpointSlice = o.APIExportEndpointSlice

	providerErr := make(chan error, 1)
	go func() {
		providerErr <- provider.Start(ctx, g)
	}()

	mode := "single-shard"
	if o.APIExportEndpointSlice != "" {
		mode = "multi-shard (apiexport=" + o.APIExportEndpointSlice + ")"
	}
	klog.InfoS("rbacprovider running", "mode", mode, "kubeconfig", o.Kubeconfig)

	// ── virtual workspaces ──────────────────────────────────────────

	// Per-workspace MCP calls impersonate the caller using the VW's
	// own kubeconfig identity; that identity needs RBAC permission to
	// impersonate users/groups/userextras in kcp.
	factory, err := mcp.NewClientFactory(restConfig)
	if err != nil {
		return fmt.Errorf("create MCP client factory: %w", err)
	}

	vws := []rootapiserver.NamedVirtualWorkspace{
		scar.NewVirtualWorkspace(g),
		mcp.NewVirtualWorkspace(g, factory),
	}

	// ── root apiserver ──────────────────────────────────────────────

	scheme := runtime.NewScheme()
	utilruntime.Must(accessv1alpha1.AddToScheme(scheme))
	codecs := serializer.NewCodecFactory(scheme)

	recommended := genericapiserver.NewRecommendedConfig(codecs)

	// The root apiserver requires an OpenAPI config to build models for
	// the served types at startup (definitions generated by openapi-gen
	// into pkg/generated/openapi).
	namer := openapinamer.NewDefinitionNamer(scheme)
	recommended.OpenAPIConfig = genericapiserver.DefaultOpenAPIConfig(generatedopenapi.GetOpenAPIDefinitions, namer)
	recommended.OpenAPIConfig.Info.Title = "kcp-access-vw"
	recommended.OpenAPIV3Config = genericapiserver.DefaultOpenAPIV3Config(generatedopenapi.GetOpenAPIDefinitions, namer)
	recommended.OpenAPIV3Config.Info.Title = "kcp-access-vw"

	rootCfg, err := rootapiserver.NewConfig(recommended)
	if err != nil {
		return fmt.Errorf("create root apiserver config: %w", err)
	}
	rootCfg.Extra.VirtualWorkspaces = vws

	if err := o.SecureServing.MaybeDefaultWithSelfSignedCerts("localhost", nil, []net.IP{netutils.ParseIPSloppy("127.0.0.1")}); err != nil {
		return fmt.Errorf("default serving certs: %w", err)
	}
	if err := o.SecureServing.ApplyTo(&recommended.Config.SecureServing); err != nil {
		return fmt.Errorf("apply secure serving: %w", err)
	}
	if err := o.Authentication.ApplyTo(&recommended.Config.Authentication, recommended.Config.SecureServing, nil); err != nil {
		return fmt.Errorf("apply authentication: %w", err)
	}
	if err := o.Authorization.ApplyTo(&recommended.Config, func() []rootapiserver.NamedVirtualWorkspace { return vws }); err != nil {
		return fmt.Errorf("apply authorization: %w", err)
	}

	// /debug/graph sits outside the VW authorizers (it is not under a
	// /services/ prefix), so grant it to authenticated users explicitly.
	recommended.Config.Authorization.Authorizer = union.New(
		recommended.Config.Authorization.Authorizer,
		pathScopedAuthorizer(debugGraphPath, virtual.AuthenticatedOnlyAuthorizer()),
	)

	completed := rootCfg.Complete()

	rootServer, err := rootapiserver.NewServer(completed, genericapiserver.NewEmptyDelegate())
	if err != nil {
		return fmt.Errorf("create root apiserver: %w", err)
	}

	// Debug endpoint: pretty-printed snapshot of the access graph.
	// Registered on the root server's non-restful mux; requests fall
	// through the VW path resolution into the generic handler chain,
	// so authentication and the authorizer above still apply.
	rootServer.GenericAPIServer.Handler.NonGoRestfulMux.HandleFunc(debugGraphPath, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(g.Snapshot())
	})

	prepared := rootServer.GenericAPIServer.PrepareRun()

	klog.InfoS("access-vw serving",
		"scar", scar.RootPath+"/apis/"+accessv1alpha1.SchemeGroupVersion.Group+"/"+accessv1alpha1.SchemeGroupVersion.Version+"/selfclusteraccessreviews",
		"mcp", mcp.RootPath,
	)

	serveErr := make(chan error, 1)
	go func() {
		serveErr <- prepared.RunWithContext(ctx)
	}()

	select {
	case err := <-providerErr:
		if err != nil && !errors.Is(err, context.Canceled) {
			return fmt.Errorf("rbac provider failed: %w", err)
		}
		<-serveErr
		return nil
	case err := <-serveErr:
		return err
	}
}

// debugGraphPath serves a pretty-printed access-graph snapshot for
// debugging. Available to any authenticated user.
const debugGraphPath = "/debug/graph"

// pathScopedAuthorizer delegates authorization for exactly one
// non-resource path and stays neutral on everything else, so it can be
// unioned with the VW authorizers without widening their scope.
func pathScopedAuthorizer(path string, delegate authorizer.Authorizer) authorizer.Authorizer {
	return authorizer.AuthorizerFunc(func(ctx context.Context, attrs authorizer.Attributes) (authorizer.Decision, string, error) {
		if !attrs.IsResourceRequest() && attrs.GetPath() == path {
			return delegate.Authorize(ctx, attrs)
		}
		return authorizer.DecisionNoOpinion, "", nil
	})
}
